version: '3.3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.5.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#       跨域问题处理
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    stdin_open: true
    tty: true
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
        # 这个在docker中启动后 死活链接不了es  
#         尝试过在es中处理跨域的问题  后来又出现403问题
#         最后是使用google的浏览器插件（跟这个东西一样的  就是个前端展示） 来进行es的监控
#   所以这里没必要再用了
#   elasticsearch-head:
#     container_name: elasticsearch-head
#     image: mobz/elasticsearch-head:5
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     ports:
#       - 9100:9100
#     links:
#       - elasticsearch:elasticsearch
#     network_mode: bridge
  kibana:
    container_name: kibana
    image: kibana:7.5.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
  logstash:
    container_name: logstash
    image: logstash:7.5.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.template.json:/usr/share/logstash/templates/logstash.template.json
    ports:
      - 5044:5044
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
  filebeat:
    user: root
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.5.0
    links:
      - logstash:logstash
    depends_on:
      - logstash
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
#       收集要监测展示的日志，将实际日志的位置挂载到 filebeat.yml中前面指定的位置
      - /home/win/jenkins-docker/data/logs/enc:/usr/share/filebeat/mylog
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: ["--strict.perms=false"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    network_mode: bridge
    deploy:
      mode: global
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
